# Generated by Django 3.2.9 on 2021-11-27 10:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('art', '0002_auto_20211127_1355'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='art',
            name='description',
        ),
    ]
