# Generated by Django 3.2.9 on 2022-01-18 16:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('art', '0003_remove_art_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='art',
            old_name='painter',
            new_name='artist',
        ),
    ]
